app/helper/indexer_helper.py

Fixes #51 
_indexers数组只增不减，遍历消耗大量时间和资源，每次添加前清空；
减少频繁调用initConfig造成的io问题（调用索引列表大概会减少300ms的延迟，但是插件增删索引站点时可能要重启生效）
bug复现方式: 在“自定义索引器”中添加站点后，一直刷新索引器界面（或者其他任何有调用索引器的操作）就会无限往_indexers里添加，元素过千时候遍历时间到秒级，会导致web越来越卡

Fixes #51 进入nastool主页响应太慢 

---

web/action.py
web/templates/site/site.html

目前添加或者更新站点失败时，直接刷新页面了，使用的人不知道发生了啥，所以添加了“添加或者更新站点失败时，弹窗提醒用户”这个功能

添加或者更新站点失败时，弹窗提醒用户

---

app/plugins/modules/cookiecloud.py

修正正则无法正确匹配domain url时报错问题
大佬改了config.get("black_list", []) or [] 后对空列表也会产生报错，后面处理的时候是str类型的，这里我改为config.get("black_list", "") or “”了

修正正则无法正确匹配domain url时报错问题

---

app/media/douban.py
web/backend/web_utils.py
web/main.py

Due to each request refreshes the cookie, usually browser will refuses to follow cache-control which returned in the response of API: /img to cache assets. This effectively leads to more asset requests are sent to doubanio (since data cached in the LRU can be easily fanned out in this app). Consequently, this results in slow image loading when accessing related pages.
the first commit reduces the requests sent to doubanio from server, image resources are now hitting the browser cache and web experiences is improved, making the LRU cache more efficient.
before:
after:
about config: SESSION_REFRESH_EACH_REQUEST
pls see: https://docs.jinkan.org/docs/flask/config.html
or you can put this in config.yaml
In second commit, I changed the default format for Douban assets to webp, which is smaller …

correct cache-control & use webp format for doubanio

---

app/message/client/telegram.py

There appears to be missing a '%s' in logging formatting.

Fix when setting Telegram Webhook failed

---

web/action.py
web/apiv1.py

WHAT's CHANGED:
A new API has been registered in the api/v1 for querying the "Continue Watching" list of the current media library. Additionally, it has been tested, and despite exposing the 'num' parameter, services like Plex are unable to return results as needed. Therefore, I manually performed list slicing within the function.

feat: expose library-resume to api/v1

---

app/downloader/downloader.py
web/action.py
web/apiv1.py

WHAT's changed: 
The /now API has following two changes:
1. An additional parameter has been added to explicitly specify the downloader ID for listing its download tasks.
2. Another parameter has been included to control whether to forcefully list all tasks within the downloader.
Both of parameters are optional, and the default behavior aligns with the current API behavior.
Furthermore, I've added the 'is_default' field in the response of the '/download/client/list' to indicate whether it is the default downloader.

feat(api/downloader): add parameters in api:/now

---

app/message/client/telegram.py
config.py
config/config.yaml
web/templates/setting/basic.html

具体搭建步骤：https://www.yuque.com/u21363723/nt6hcz/whq99ankmn87arcq?singleDoc 
并支持在后台 - 设置 - 基础设置 - 实验室 - Telegram Bot Api 代理 填写已经搭建好的域名
发送消息测试

使用Cloudflare Worker搭建Telegram Bot Api 代理

---

app/indexer/client/_base.py

tmdb项目没有年份时直接忽略，修复报错导致搜不到结果 且前后数量不匹配

fix: indexer 处理没有tmdb没有年份项目时出错

---

app/utils/torrent.py

fix: torrent path with '/'

---

app/media/meta/metaanime.py

现有逻辑在 `anitopy` 匹配失败后默认会使用第一个方框内的名字作为番剧标题，但更常见的命名方式中，第一个框内为字幕组名，此 PR 修复了这个问题。
举例：
当标题为: `[Billion Meta Lab][憧憬成为魔法少女][01][1080p][AT-X][简体内嵌]` 时，现有逻辑最后会 fallback 到 `Billion Meta Lab` 上，而在此 PR 中，若自定义了番剧组 `Billion Meta Lab`，则会使用真实标题。

optim: title matcher when anitopy failed

---

config.py

fix: telegram api 代理默认值无法编辑为空

---

app/filetransfer.py

有些电影的数据不全，甚至没有发行年份，例如 tmdb id 1079858。这种情况下
设置年代为0.
注意: 这种情况下，短年代格式会显示 0s, 长年代格式会显示为 0-9s.

filetransfer: 当没有年份的时候年代设置为0

---

app/brushtask.py

当刷流种子被各种条件限制时会导致后续即使条件符合也没法刷流
这些条件很多都是变动的，如：
- 包含规则、排除规则（会根据页面修改变动）
- 站点流控（随时可变）
- 免费\hr状态（种子类型可能随时变化）
- 做种人数
- 下载、上传限制速度
- 正在下载的任务数
当条件变动后，之前检查的种子应该要继续检查，原先只要种子一次检查失败就不会再检查了，会导致很多种子因此无法下载刷流

fix(brushtask): 修复刷流任务bug

---

app/brushtask.py
web/action.py
web/apiv1.py
web/templates/site/brushtask.html

+ 新增：刷流任务 支持当前站点任务总数限制（需为站点或刷流任务添加标签）
+ 新增：刷流任务 支持当前站点下载中任务数限制（需为站点或刷流任务添加标签）
感谢大佬一直以来继续维护 nas-tools，不知道我的这个需求算不算小众，如果实在没必要的话大佬把 PR 关掉就行。
最后祝大家新年快乐~

feat(brushtask): 支持当前站点任务数限制

---

app/utils/string_utils.py
config/config.yaml
web/templates/setting/basic.html

选项默认关闭，与修改前行为一致。
起因是 tinyMediaManager 刮削的文件名与 nas-tools 刮削的不一样，一看是 nas-tools 在净化文件名时将中文逗号和问号删掉了：[string_utils.py#L309](https://github.com/hsuyelin/nas-tools/blob/1c41cd43508e877b520027c70b23f1567ab34561/app/utils/string_utils.py#L309)，而这两个符号在文件系统中是允许的。
不知道当初这段代码的作者有什么特殊考虑，删了问号逗号没删句号，所以加个开关允许更改行为。

feat(media): 将删除特殊字符改为选项控制

---

app/helper/db_helper.py
app/helper/words_helper.py
app/media/media.py
app/media/meta/metainfo.py

在以前的逻辑中，自定义识别词是一个单例。所有的识别词，无论是全局自定义识别词还是根据影视来分组的识别词都会应用到所有影视的名称识别中；现在，名称识别将真正根据自定义识别词中的分组来进行应用。
我在编写这个 pr 前，纠结了许久是否应该更改这个逻辑，毕竟这个逻辑存在已久却没有人提出疑问。也许以前的设计理念只是起分组作用，方便用户记忆当初识别词是为哪个影视而编写的；但是在 web 页面中，通用分组的标识让我更加坚定原来的逻辑是不符合原来的设计理念的；同时，原来的 `get_custom_word_groups` 方法设计了 `tmdbid` 的字段却在全文中没有使用，这更让我坚定了这是原来就要实现的逻辑。也希望大家一起考虑一下这部分究竟应该如何实现。

修复自定义识别词不使用媒体分组的问题

---

app/media/media.py
app/media/meta/metainfo.py

因为依赖 `MetaInfo` 接口的函数众多，所以将 TMDB 查询逻辑由 `get_media_info` 移至 `MetaInfo`，这样应该处处都是按照正确的逻辑来应用自定义词组了。

[重要] 修复 #684 导致的仅通用自定义识别词组被应用的问题

---

app/message/client/slack.py

slack通知如果发送到私人频道会报错
```
slack 发送测试消息失败：The request to the Slack API failed. (url: https://www.slack.com/api/chat.postMessage) The server responded with: {'ok': False, 'error': 'channel_not_found'}
```
此修改支持将消息发送到私人频道

feat: slack 消息通知支持私人频道

---

web/main.py

基于 #600 修改
感谢 @PterX 
我认为这种身份认证属于`forward_auth` 而不是 `oidc` :)
所以我将oidc修改为forward_auth
添加 trusted_proxies 防止伪造header
添加 forward_auth_header 允许修改forward_auth获取用户的header
修改后的配置文件样式如下
```yaml
...
app:
forward_auth:
enable: true
trusted_proxies:
- 192.168.1.0/24
header: X-Forward-Auth-Username
...
```

feat: forward_auth

---

web/templates/rename/mediafile.html

+ 修复当文件夹路径中包含单引号时引发报错导致无法列举文件夹内容
例如：`[LPSub&LP-Raws] BanG Dream! It's MyGO!!!!! [BD 01-13 Fin][AVC AAC][1080p][JPSC]`

fix: mediafile.html failed to list dir when "'" in path

---

app/downloader/downloader.py
app/media/meta/metainfo.py

修复纵使种子内的文件名含有所有需要的剧集时，如果标题或副标题没有写明集数范围时，该种子也不会被下载的问题。本 pr 同时修复了副标题仅应用自定义识别词中通用识别词的问题。

修复纵使种子内的文件名含有所有需要的剧集时，如果标题或副标题没有写明集数范围时，该种子也不会被下载的问题

---

app/message/client/slack.py

修复：与机器人私聊时，机器人会将结果回复至Nastools中设置的频道（或默认的全体），而非回复至私聊窗口的问题（频道中@，机器人会正常回复@它的用户）
很早前Slack修改了APi接口，不能再以用户名作为频道名，我自己很早改的，看见这还有在维护nastool，就放这好了。

Fix: Slack direct Message(修复私聊却回复至频道的问题)
